using UnityEngine;

[CreateAssetMenu(fileName = "Default Player Data", menuName = "Custom/Player", order = 0)]
public class PlayerData : ScriptableObject
{
    [SerializeField] private float _defaultSpeed;
    [SerializeField] private float _sneakSpeed;
    [SerializeField] private float _runSpeed;
    [SerializeField] private float _defaultJumpHeight;
    [SerializeField] private float _sneakJumpHeight;
    [SerializeField] private float _runJumpHeight;
    [SerializeField] private float _maxStamina;
    [SerializeField] private float _staminaTimeToRegen;
    [SerializeField] private float _staminaDecreasePerFrame;
    [SerializeField] private float _staminaIncreasePerFrame;
    [SerializeField] private float _runJumpStaminaDecrease;
    [SerializeField] private float _maxPower;
    [SerializeField] private float _powerIncreasePerFrame;
    [SerializeField] private float _flashDistance;
    [SerializeField] private float _flashCooldown;
    [SerializeField] private int _numberOfFlashes;
    [SerializeField] private int _numberOfEnergyDrinks;
    [SerializeField] private int _numberOfBottles;
    [SerializeField] private float _defaultHearingZoneRadius;
    [SerializeField] private float _walkHearingZoneRadius;
    [SerializeField] private float _sneakHearingZoneRadius;
    [SerializeField] private float _runHearingZoneRadius;
    [SerializeField] private float _landingHearingZoneCoefficient;
    [SerializeField] private float _mouseSensitivity;
    [SerializeField] private int _numberOfFlashesToAdd;
    [SerializeField] private int _numberOfEnergyDrinksToAdd;
    [SerializeField] private int _numberOfBottlesToAdd;
    [SerializeField] private float _flashDistanceToAdd;
    [SerializeField] private float _flashCooldownToDecrease;
    [SerializeField] private float _defaultLightIntensity;
    [SerializeField] private float _flashLightIntensity;
    [SerializeField] private float _waitForDeath;
    
    public float DefaultSpeed => _defaultSpeed;
    public float SneakSpeed => _sneakSpeed;
    public float RunSpeed => _runSpeed;
    public float DefaultJumpHeight => _defaultJumpHeight;
    public float SneakJumpHeight => _sneakJumpHeight;
    public float RunJumpHeight => _runJumpHeight;
    public float MaxStamina => _maxStamina;
    public float StaminaTimeToRegen => _staminaTimeToRegen;
    public float StaminaDecreasePerFrame => _staminaDecreasePerFrame;
    public float StaminaIncreasePerFrame => _staminaIncreasePerFrame;
    public float RunJumpStaminaDecrease => _runJumpStaminaDecrease;
    public float MaxPower => _maxPower;
    public float PowerIncreasePerFrame => _powerIncreasePerFrame;
    public float FlashDistance => _flashDistance;
    public float FlashCooldown => _flashCooldown;
    public int NumberOfFlashes => _numberOfFlashes;
    public int NumberOfEnergyDrinks => _numberOfEnergyDrinks;
    public int NumberOfBottles => _numberOfBottles;
    public float DefaultHearingZoneRadius => _defaultHearingZoneRadius;
    public float WalkHearingZoneRadius => _walkHearingZoneRadius;
    public float SneakHearingZoneRadius => _sneakHearingZoneRadius;
    public float RunHearingZoneRadius => _runHearingZoneRadius;
    public float LandingHearingZoneCoefficient => _landingHearingZoneCoefficient;
    public float MouseSensitivity => _mouseSensitivity;
    public int NumberOfFlashesToAdd => _numberOfFlashesToAdd;
    public int NumberOfEnergyDrinksToAdd => _numberOfEnergyDrinksToAdd;
    public int NumberOfBottlesToAdd => _numberOfBottlesToAdd;
    public float FlashDistanceToAdd => _flashDistanceToAdd;
    public float FlashCooldownToDecrease => _flashCooldownToDecrease;
    public float DefaultLightIntensity => _defaultLightIntensity;
    public float FlashLightIntensity => _flashLightIntensity;
    public float WaitForDeath => _waitForDeath;
}
